/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "find.h"

float *
bigger_100_svc(operandos *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	//printf("BIGGER\n");
	float bigger = argp->vet[0];
	
	for(int i=1; i<10; i++)
	{
		if(argp->vet[i] > bigger)
			bigger = argp->vet[i];
	}

	result = bigger;

	return &result;
}

float *
smaller_100_svc(operandos *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	float smaller = argp->vet[0];

	for(int i=1; i<10; i++)
	{
		if(argp->vet[i] < smaller)
			smaller = argp->vet[i];
	}

	result = smaller;

	return &result;
}
