/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "find.h"


void
prog_100(char *host)
{
	CLIENT *clnt;
	float  *result_1;
	operandos  bigger_100_arg;
	float  *result_2;
	operandos  smaller_100_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PROG, VERSAO, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = bigger_100(&bigger_100_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = smaller_100(&smaller_100_arg, clnt);
	if (result_2 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

float bigger(CLIENT *clnt, float vet[])
{
	operandos ops;
	float *result;

	for(int i=0; i<10; i++)
		ops.vet[i] = vet[i];

	/* chama o stub do cliente */
	result = bigger_100(&ops, clnt);

	if(result == NULL)
	{
		fprintf(stderr,"Problema na chamada RPC\n");
		exit(0);
	}

	return(*result);
}

float smaller(CLIENT *clnt, float vet[])
{
	operandos ops;
	float *result;

	for(int i=0; i<10; i++)
		ops.vet[i] = vet[i];

	/* chama o stub do cliente */
	result = smaller_100(&ops, clnt);

	if(result == NULL)
	{
		fprintf(stderr, "Problema na chamada do RPC\n");
		exit(0);
	}

	return (*result);
}


int main (int argc, char *argv[])
{
	CLIENT *clnt;
	float vet[10];

	clnt = clnt_create(argv[1], PROG, VERSAO, "udp");

	if (clnt == (CLIENT *) NULL)
	{
		clnt_pcreateerror(argv[1]);
		exit(1);
	}

	/* generate values */
	for(int i=0; i<10; i++)
		vet[i] = i;

	printf("BIGGER: %f\n",bigger(clnt, vet));
	printf("SMALLER: %f\n", smaller(clnt, vet));

}
